In [263]:
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib as mtp
import seaborn as sns

In [175]:
# Python program to change the current working directory
# Function to Get the current
# working directory
def current_path():
    print("Current working directory before")
    print(os.getcwd())
    print()
# Driver's code
# Printing CWD before
current_path()
# Changing the CWD
os.chdir('C:/Users/markk/OneDrive/Documents/Documents/Data Science/DSProjects/ml-zoomcamp/session1')
# Printing CWD after
current_path()

Current working directory before
C:\Users\markk\OneDrive\Documents\Documents\Data Science\DSProjects\ml-zoomcamp\session1

Current working directory before
C:\Users\markk\OneDrive\Documents\Documents\Data Science\DSProjects\ml-zoomcamp\session1



## Questions 1 & 2

## Numpy and Pandas Versions

In [176]:
print('numpy: ',np.__version__, 'pandas: ',pd.__version__)

numpy:  1.17.0 pandas:  1.1.5


## Read in CSV File as Pandas DataFrame, check shape

In [177]:
carsdata = pd.read_csv('data.csv')
# dfcars = pd.DataFrame('data')
carsdata.shape

(11914, 16)

In [178]:
carsdata.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [179]:
carsdata.columns = carsdata.columns.str.lower().str.replace(' ', '_')
carsdata.head(2)

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650

## Question 3: What is the Average MSPR of BMW cars?

In [180]:
BMW = carsdata[carsdata['make'] == 'BMW']
# carsdata.groupby('MSRP').MSRP.mean()
BMW.head(2)

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650

In [181]:
print('BMW Avg MSRP:',BMW['msrp'].mean().round(2))

BMW Avg MSRP: 61546.76


## Question 4: 2015 Subset
Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [182]:
cars2015=carsdata[carsdata['year'] > 2014]
cars2015.head(2)
cars2015.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        0
engine_hp              51
engine_cylinders        8
transmission_type       0
driven_wheels           0
number_of_doors         5
market_category      1324
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64

## Question 5
    Calculate the average "Engine HP" in the dataset.
    Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
    Now, calcualte the average of "Engine HP" again.
    Has it changed?
Round both means before answering this questions. You can use the round function for that:

In [184]:
BAvgHP = carsdata['engine_hp'].mean().round(2)
print("Avg HP Before: ",BAvgHP)
carsdata.engine_hp = carsdata.engine_hp.fillna(carsdata.engine_hp.mean())
print(carsdata.isnull().sum())
AAvgHP = carsdata['engine_hp'].mean().round(2)
print("Avg HP After: ",AAvgHP)

Avg HP Before:  249.39
make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp               0
engine_cylinders       30
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64
Avg HP After:  249.39


### Need to create Before and After Separately, before and after the fillna

 ## Question 6

    Select all the "Rolls-Royce" cars from the dataset.
    Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
    Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Invert XTX.
    What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time

In [196]:
RR = carsdata[carsdata['make'] == 'Rolls-Royce']
RR.head(2)

make     model  year             engine_fuel_type  engine_hp  \
2921  Rolls-Royce  Corniche  2001  premium unleaded (required)      325.0   
3505  Rolls-Royce      Dawn  2016  premium unleaded (required)      563.0   

      engine_cylinders transmission_type     driven_wheels  number_of_doors  \
2921               8.0         AUTOMATIC  rear wheel drive              2.0   
3505              12.0         AUTOMATIC  rear wheel drive              2.0   

                     market_category vehicle_size vehicle_style  highway_mpg  \
2921                   Exotic,Luxury        Large   Convertible           15   
3505  Exotic,Luxury,High-Performance        Large   Convertible           19   

      city_mpg  popularity    msrp  
2921        10          86  359990  
3505        12          86  335000

In [211]:
RR2 = RR[['engine_hp','engine_cylinders','highway_mpg']].drop_duplicates()
RR2

engine_hp  engine_cylinders  highway_mpg
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [212]:
x = RR2.values
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [273]:
#Transpose x
x_trans = x.T
print("Transpose of X: ",x_trans)

#Matrix Matrix Mult of x & Transpose of x
XTX = x.dot(x_trans)
print("Matrix-Matrix Mult of x & its transpose: ",XTX)

#INVERT XTX
#Number of rows equals number of columns, must be square matrix
# XTXs = XTX[[0,1,2]] #square matrix
#Use Linalg library to find the inverse matrix
XTXinv = np.linalg.inv(XTX)
XTXinv
#This does not look right

Transpose of X:  [[325. 563. 563. 563. 322. 453. 624.]
 [  8.  12.  12.  12.  12.  12.  12.]
 [ 15.  19.  21.  20.  15.  19.  21.]]
Matrix-Matrix Mult of x & its transpose:  [[105914. 183356. 183386. 183371. 104971. 147606. 203211.]
 [183356. 317474. 317512. 317493. 181715. 255544. 351855.]
 [183386. 317512. 317554. 317533. 181745. 255582. 351897.]
 [183371. 317493. 317533. 317513. 181730. 255563. 351876.]
 [104971. 181715. 181745. 181730. 104053. 146295. 201387.]
 [147606. 255544. 255582. 255563. 146295. 205714. 283215.]
 [203211. 351855. 351897. 351876. 201387. 283215. 389961.]]


array([[ 2.26655979e+10,  1.31639849e+11,  6.00619990e+10,
         6.00514968e+09, -3.30011828e+10, -2.43060764e+10,
        -1.55510137e+11],
       [-3.27415886e+14, -1.81277359e+15, -1.62961971e+15,
         6.77449931e+14,  1.21383250e+14,  9.46190933e+14,
         1.91564644e+15],
       [ 3.76975783e+15,  1.38681644e+16,  6.30933989e+15,
        -7.54480926e+15, -1.37638987e+15, -4.08171120e+15,
        -9.68776581e+15],
       [ 1.92477705e+15,  5.61962212e+15,  2.10780469e+15,
        -3.28629886e+15, -3.28648700e+14, -2.02813806e+15,
        -3.36752589e+15],
       [ 1.03705184e+15,  4.30192234e+15,  2.42889709e+15,
        -2.15278424e+15, -4.23061002e+14, -1.43782129e+15,
        -3.40852079e+15],
       [-3.74611682e+15, -1.39027387e+16, -6.71094389e+15,
         7.42405523e+15,  1.31210760e+15,  4.38132983e+15,
         9.99360111e+15],
       [-2.65806912e+15, -8.07428433e+15, -2.50551812e+15,
         4.88238320e+15,  6.94630722e+14,  2.22016600e+15,
         4.5546686

In [261]:
#Find dot product (multiply two matrices) of XTX and XTXinv - should be identity matrix
XTXinv.dot(XTX)

array([[ 1.08145718e+06,  1.87246240e+06,  1.87270641e+06,
         1.87258041e+06,  1.07178633e+06,  1.50723440e+06,
         2.07524500e+06],
       [ 6.05898630e+07,  1.05065115e+08,  1.05069325e+08,
         1.05001684e+08,  6.01542470e+07,  8.45813710e+07,
         1.16524413e+08],
       [ 6.25837580e+07,  1.07777206e+08,  1.07659930e+08,
         1.08505000e+08,  6.18722700e+07,  8.62042780e+07,
         1.19189370e+08],
       [-1.22361768e+08, -2.11228114e+08, -2.11105506e+08,
        -2.11428954e+08, -1.21170264e+08, -1.70280706e+08,
        -2.34618202e+08],
       [ 2.63130500e+05,  8.32136500e+05,  5.24531500e+05,
         5.47262000e+05,  1.96458500e+05,  3.23736500e+05,
         4.43035500e+05],
       [-8.49112000e+05, -1.95583200e+06, -1.74804000e+06,
        -1.32764800e+06, -7.73080000e+05, -9.84824000e+05,
        -8.99528000e+05],
       [-2.23391000e+05, -6.15091000e+05, -7.51157000e+05,
        -4.20980000e+05, -2.12479000e+05, -2.80339000e+05,
        -5.9600500

In [266]:
XTX

array([[105914., 183356., 183386., 183371., 104971., 147606., 203211.],
       [183356., 317474., 317512., 317493., 181715., 255544., 351855.],
       [183386., 317512., 317554., 317533., 181745., 255582., 351897.],
       [183371., 317493., 317533., 317513., 181730., 255563., 351876.],
       [104971., 181715., 181745., 181730., 104053., 146295., 201387.],
       [147606., 255544., 255582., 255563., 146295., 205714., 283215.],
       [203211., 351855., 351897., 351876., 201387., 283215., 389961.]])

## Questions 7

    Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the value of the first element of w?.

    Note: You just implemented linear regression. We'll talk about it in the next lesson.


In [270]:
y = [1000, 1100, 900, 1200, 1000, 850, 1200]
y

[1000, 1100, 900, 1200, 1000, 850, 1200]

In [272]:
w = XTXinv * x_trans * y

ValueError: operands could not be broadcast together with shapes (7,7) (3,7) 

In [275]:
os.getcwd()

'C:\\Users\\markk\\OneDrive\\Documents\\Documents\\Data Science\\DSProjects\\ml-zoomcamp\\session1'